### ISSUE TITLE
Using ranch instead of custom gen_tcp code 

### ISSUE THREAD

**Issue by WolfDan** [sgessa/ms2ex#11]
[ranch](https://github.com/ninenines/ranch) uses `gen_tcp` under the hood, it's the main component of cowboy which is used by phoenix for all http request related stuff

ranch manages things like acceptor pools, connections pools, maximum number of accepted connections and so on as well it's battle tested from phoenix and more 

rather than reinventing the wheel we could just use ranch and simplify the network code

**Comment by sgessa** [comment]
I agree. As you can see [here](https://github.com/sgessa/ms2ex/blob/3ebbde82acacf11b0a47030dec0e2d935f187330/lib/ms2ex/net/servers/game_server.ex), the first commit of ms2ex implemented ranch, it's been a while and I cannot remember why I had to move away from it.
Anyway if we can make it work and we can simplify the current code it would be great.

**Comment by sgessa** [comment]
[This](https://github.com/sgessa/ms2ex/commit/128e423731494b14813f8b37441f63173a5f78af) is when we moved away from ranch
